# Generated by Django 5.0.6 on 2024-07-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='bookinganalytics',
            old_name='canceled_bookings',
            new_name='completed_appointments',
        ),
        migrations.RenameField(
            model_name='bookinganalytics',
            old_name='completed_bookings',
            new_name='pending_appointments',
        ),
        migrations.RenameField(
            model_name='bookinganalytics',
            old_name='total_bookings',
            new_name='total_appointments',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselors.counselor'),
        ),
        migrations.AlterField(
            model_name='bookinganalytics',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselors.counselor'),
        ),
    ]
