# Generated by Django 5.0.7 on 2024-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('research_areas', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='counselors/')),
                ('cv_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
