# Generated by Django 5.0.6 on 2024-07-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='counselor',
            name='office_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='counselor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='counselors/'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='research_areas',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
