# Generated by Django 5.0.7 on 2024-08-04 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Full name must contain only letters', regex="^[A-Za-z\\s'-]+$")])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be a valid KNUST student email', regex='^[a-zA-Z0-9._%+-]+@st\\.knust\\.edu\\.gh$')])),
                ('phone_number', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=200)),
                ('office_visit_info', models.CharField(max_length=200)),
            ],
        ),
    ]
